### ISSUE TITLE
Feature Request: Auto Black & White Mode for Specific Sites

### ISSUE THREAD

**Issue by chayanforyou** [azrafe7/blackAndWhiteWeb#1]
Hi,

First of all, thank you for creating such an awesome extension! It has been incredibly helpful.

I was wondering if you could add a feature to automatically trigger the Black & White mode for specific websites. For example, if I enable Black & White mode for `facebook.com`, the extension could save this setting. Then, the next time I visit `facebook.com`, the mode would automatically turn on without requiring manual activation.

This feature would greatly improve the convenience and usability of the extension.

**Comment by azrafe7** [comment]
Hi, and glad you liked it! 😉 

Hopefully your use-case is already implemented.
In the Options page of the extension:
 - check ALWAYS ON
 - check ALWAYS ON - White List
 - in the WHITE LIST add something like "facebook.com"
 - save
 - open a new facebook tab
 
Check out this short video: 
https://github.com/user-attachments/assets/4bf0bd6f-8415-4123-a19d-c8cdf3480a7f

Let me know how it works for you.

**Comment by chayanforyou** [comment]
Cool, Its working fine.

Thanks bro :)
